#############################################################################
# Makefile for building: openfly.app/Contents/MacOS/openfly
# Generated by qmake (3.0) (Qt 5.0.0) on: Sat Nov 10 15:40:28 2012
# Project:  OpenFly.pro
# Template: app
# Command: /Volumes/Code/qt-shadowbuilds/qt-base-ios-device/bin/qmake -spec macx-xcode -o openfly.xcodeproj/project.pbxproj OpenFly.pro
#############################################################################

MOC       = /Volumes/Code/qt-shadowbuilds/qt-base-ios-device/bin/moc
UIC       = /Volumes/Code/qt-shadowbuilds/qt-base-ios-device/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DTARGET="openfly" -DVERSION="1.0.0" -DQT_DECLARATIVE_LIB -DQT_WIDGETS_LIB -DQT_SCRIPT_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH       = -I../../../qt-src/qt-base-ios/mkspecs/macx-xcode -I. -I../../OpenFly -I../../../qt-shadowbuilds/qt-base-ios-device/include -I../../../qt-shadowbuilds/qt-base-ios-device/include/QtDeclarative -I../../../qt-shadowbuilds/qt-base-ios-device/include/QtWidgets -I../../../qt-shadowbuilds/qt-base-ios-device/include/QtScript -I../../../qt-shadowbuilds/qt-base-ios-device/include/QtNetwork -I../../../qt-shadowbuilds/qt-base-ios-device/include/QtGui -I../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore -I. -I/usr/local/include -I/System/Library/Frameworks/CarbonCore.framework/Headers -I.
DEL_FILE  = rm -f
MOVE      = mv -f

IMAGES = 
PARSERS =
preprocess: $(PARSERS) compilers
clean preprocess_clean: parser_clean compiler_clean

parser_clean:
check: first

docs:

install_docs:

uninstall_docs:

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compilers: ./qrc_fly.cpp ./moc_receiver.cpp ./moc_xmldatasource.cpp ./moc_airportnames.cpp\
	 ./moc_flightstatuses.cpp ./moc_flighttimes.cpp ./moc_flightsmodel.cpp\
	 ./moc_settings.cpp
compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_fly.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_fly.cpp
qrc_fly.cpp: ../fly.qrc
	/Volumes/Code/qt-shadowbuilds/qt-base-ios-device/bin/rcc -name fly ../fly.qrc -o qrc_fly.cpp

compiler_moc_header_make_all: moc_receiver.cpp moc_xmldatasource.cpp moc_airportnames.cpp moc_flightstatuses.cpp moc_flighttimes.cpp moc_flightsmodel.cpp moc_settings.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_receiver.cpp moc_xmldatasource.cpp moc_airportnames.cpp moc_flightstatuses.cpp moc_flighttimes.cpp moc_flightsmodel.cpp moc_settings.cpp
moc_receiver.cpp: ../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtNetwork \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtGui \
		../node.h \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QString \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QHash \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QList \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QStack \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QSharedData \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QSharedDataPointer \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QDebug \
		../receiver.h
	/Volumes/Code/qt-shadowbuilds/qt-base-ios-device/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__=4 ../receiver.h -o moc_receiver.cpp

moc_xmldatasource.cpp: ../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QHash \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QObject \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QBasicTimer \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QDateTime \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QUrl \
		../xmldatasource.h
	/Volumes/Code/qt-shadowbuilds/qt-base-ios-device/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__=4 ../xmldatasource.h -o moc_xmldatasource.cpp

moc_airportnames.cpp: ../xmldatasource.h \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QHash \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QObject \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QBasicTimer \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QDateTime \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QUrl \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QStringList \
		../airportnames.h
	/Volumes/Code/qt-shadowbuilds/qt-base-ios-device/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__=4 ../airportnames.h -o moc_airportnames.cpp

moc_flightstatuses.cpp: ../xmldatasource.h \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QHash \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QObject \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QBasicTimer \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QDateTime \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QUrl \
		../flightstatuses.h
	/Volumes/Code/qt-shadowbuilds/qt-base-ios-device/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__=4 ../flightstatuses.h -o moc_flightstatuses.cpp

moc_flighttimes.cpp: ../xmldatasource.h \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QHash \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QObject \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QBasicTimer \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QDateTime \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QUrl \
		../flighttimes.h
	/Volumes/Code/qt-shadowbuilds/qt-base-ios-device/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__=4 ../flighttimes.h -o moc_flighttimes.cpp

moc_flightsmodel.cpp: ../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QAbstractListModel \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QStringList \
		../flighttimes.h \
		../xmldatasource.h \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QHash \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QObject \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QBasicTimer \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QDateTime \
		../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QUrl \
		../flightsmodel.h
	/Volumes/Code/qt-shadowbuilds/qt-base-ios-device/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__=4 ../flightsmodel.h -o moc_flightsmodel.cpp

moc_settings.cpp: ../../../qt-shadowbuilds/qt-base-ios-device/include/QtCore/QSettings \
		../settings.h
	/Volumes/Code/qt-shadowbuilds/qt-base-ios-device/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__=4 ../settings.h -o moc_settings.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

